# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "sinatra"
#gem "activerecord"
gem "mysql2"
gem "unicorn"
gem "json"
gem "apns"
gem "dimensions"
gem "fastimage_resize"
gem "ZenTest", ">=4.3"
